server:
  port: 7090
#spring:

spring:
  application:
    name: searchManager
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hunauforum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall,log4j
      initialSize: 5
      maxActive: 200
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minIdle: 20
      useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: ''
    # 连接超时时间
    timeout: 3000
    port: 6379
  elasticsearch:
    uris: [localhost:9200]
    UserName: elastic #账号
    Password: 123456 #你的elasticsearch密码


swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://localhost:${server.port}







eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123@localhost:8761/eureka/,http://root:123@localhost:8762/eureka/
      #将provider注册到每个注册中心

#度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown #开启shutdown端点访问
  endpoint:
    shutdown:
      enabled: true  #开启shutdown 实现优雅停服
      # /actuator/shutdown 以post请求发送 则会停止该微服务



logging:
  level:
    org:
      springframework: DEBUG
      springframework.data.elasticsearch.repository: DEBUG

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/**/mapper/*.xml


page helper:
  offsetAsPageNum: true
  pageSizeZero: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  reasonable: false
  rowBoundsWithCount: true
  supportMethodsArguments: false