server:
  port: 7010
#spring:

spring:
  application:
    name: verificationCodeManager
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hunauforum?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
     filters: stat,wall,log4j
     initialSize: 5
     maxActive: 200
     maxPoolPreparedStatementPerConnectionSize: 20
     maxWait: 60000
     minIdle: 20
     useGlobalDataSourceStat: true
  #  SBA监控地址
  boot:
    admin:
      client:
        url: http://localhost:9090
  redis:
    database: 0
    host: 192.168.64.101
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: ''
    # 连接超时时间
    timeout: 3000
    port: 6379
  mail:
    host: smtp.qq.com    #邮箱服务器地址
    username: 2206101625@qq.com   #邮箱账号
    password: oseljxupkqmdecbb      #邮箱授权码
    default-encoding: utf-8    #默认编码
    protocol: smtp #发送邮件协议
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      from: 2206101625@qq.com  #邮件发件人
  thymeleaf:
    prefix: classpath:/mail/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    mode: HTML5






swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://localhost:${server.port}







eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123@localhost:8761/eureka/,http://root:123@localhost:8762/eureka/
      #将provider注册到每个注册中心

#度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" #开启shutdown端点访问
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true  #开启shutdown 实现优雅停服
      # /actuator/shutdown 以post请求发送 则会停止该微服务



logging:
  level:
    org:
      springframework: DEBUG

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/**/mapper/*.xml


page helper:
  offsetAsPageNum: true
  pageSizeZero: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  reasonable: false
  rowBoundsWithCount: true
  supportMethodsArguments: false


